In [1]:
import numpy as np
import pandas as pd
df = pd.read_csv('/content/crimes_against_women_2001-2014.csv')

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10677 entries, 0 to 10676
Data columns (total 11 columns):
 #   Column                                               Non-Null Count  Dtype
---  ------                                               --------------  -----
 0   Unnamed: 0                                           10677 non-null  int64
 1   STATE/UT                                             10677 non-null  object
 2   DISTRICT                                             10677 non-null  object
 3   Year                                                 10677 non-null  int64
 4   Rape                                                 10677 non-null  int64
 5   Kidnapping and Abduction                             10677 non-null  int64
 6   Dowry Deaths                                         10677 non-null  int64
 7   Assault on women with intent to outrage her modesty  10677 non-null  int64
 8   Insult to modesty of Women                           10677 non-null  int64
 9   Cruelty by Husband or his Relatives                  10677 non-null  int64
 10  Importation of Girls                                 10677 non-null  int64
dtypes: int64(9), object(2)
memory usage: 917.7+ KB

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10677 entries, 0 to 10676
Data columns (total 11 columns):
 #   Column                                               Non-Null Count  Dtype
---  ------                                               --------------  -----
 0   Unnamed: 0                                           10677 non-null  int64
 1   STATE/UT                                             10677 non-null  object
 2   DISTRICT                                             10677 non-null  object
 3   Year                                                 10677 non-null  int64
 4   Rape                                                 10677 non-null  int64
 5   Kidnapping and Abduction                             10677 non-null  int64
 6   Dowry Deaths                                         10677 non-null  int64
 7   Assault on women with intent to outrage her modesty  10677 non-null  int64
 8   Insult to modesty of Women                           10677 non-null  int64
 9   Cruelty by Husband or his Relatives                  10677 non-null  int64
 10  Importation of Girls                                 10677 non-null  int64
dtypes: int64(9), object(2)
memory usage: 917.7+ KB

In [3]:
df.head()

,Unnamed: 0,STATE/UT,DISTRICT,Year,Rape,Kidnapping and Abduction,Dowry Deaths,Assault on women with intent to outrage her modesty,Insult to modesty of Women,Cruelty by Husband or his Relatives,Importation of Girls
0,0,ANDHRA PRADESH,ADILABAD,2001,50,30,16,149,34,175,0
1,1,ANDHRA PRADESH,ANANTAPUR,2001,23,30,7,118,24,154,0
2,2,ANDHRA PRADESH,CHITTOOR,2001,27,34,14,112,83,186,0
3,3,ANDHRA PRADESH,CUDDAPAH,2001,20,20,17,126,38,57,0
4,4,ANDHRA PRADESH,EAST GODAVARI,2001,23,26,12,109,58,247,0

In [4]:
df[df['STATE/UT']=='BIHAR']

,Unnamed: 0,STATE/UT,DISTRICT,Year,Rape,Kidnapping and Abduction,Dowry Deaths,Assault on women with intent to outrage her modesty,Insult to modesty of Women,Cruelty by Husband or his Relatives,Importation of Girls
71,71,BIHAR,ARARIA,2001,93,13,11,3,0,50,0
72,72,BIHAR,ARWAL,2001,0,0,7,11,0,14,0
73,73,BIHAR,AURANGABAD,2001,16,4,33,13,2,19,0
74,74,BIHAR,BAGAHA,2001,25,6,0,4,0,2,0
75,75,BIHAR,BANKA,2001,34,10,9,0,0,16,0
...,...,...,...,...,...,...,...,...,...,...,...
8331,8331,BIHAR,SITAMARHI,2012,20,143,30,0,0,100,0
8332,8332,BIHAR,SIWAN,2012,20,166,64,2,0,101,0
8333,8333,BIHAR,SUPAUL,2012,20,90,15,0,0,79,0
8334,8334,BIHAR,VAISHALI,2012,20,171,62,1,0,196,0
8335,8335,BIHAR,TOTAL,2012,927,3789,1275,118,37,3686,4

In [5]:
df[df['DISTRICT']=='BHAGALPUR']

,Unnamed: 0,STATE/UT,DISTRICT,Year,Rape,Kidnapping and Abduction,Dowry Deaths,Assault on women with intent to outrage her modesty,Insult to modesty of Women,Cruelty by Husband or his Relatives,Importation of Girls
79,79,BIHAR,BHAGALPUR,2001,35,9,20,15,0,52,0
795,795,BIHAR,BHAGALPUR,2002,40,51,19,10,0,26,0
1517,1517,BIHAR,BHAGALPUR,2003,45,57,13,33,0,107,0
2245,2245,BIHAR,BHAGALPUR,2004,63,59,12,13,0,226,0
2977,2977,BIHAR,BHAGALPUR,2005,75,52,18,15,0,55,0
3710,3710,BIHAR,BHAGALPUR,2006,43,44,19,19,1,22,0
4450,4450,BIHAR,BHAGALPUR,2007,25,59,21,33,2,16,0
5193,5193,BIHAR,BHAGALPUR,2008,35,98,27,35,5,120,0
5955,5955,BIHAR,BHAGALPUR,2009,28,44,15,2,0,47,0
6727,6727,BIHAR,BHAGALPUR,2010,22,80,20,12,0,42,0
7506,7506,BIHAR,BHAGALPUR,2011,23,94,12,10,0,17,0
8299,8299,BIHAR,BHAGALPUR,2012,31,106,24,0,4,119,0
9112,95,Bihar,BHAGALPUR,2013,51,123,19,40,0,115,0

In [6]:
df[(df['STATE/UT']=='BIHAR') & (df['DISTRICT']=='BHAGALPUR') & (df['Year']<=2010)]

,Unnamed: 0,STATE/UT,DISTRICT,Year,Rape,Kidnapping and Abduction,Dowry Deaths,Assault on women with intent to outrage her modesty,Insult to modesty of Women,Cruelty by Husband or his Relatives,Importation of Girls
79,79,BIHAR,BHAGALPUR,2001,35,9,20,15,0,52,0
795,795,BIHAR,BHAGALPUR,2002,40,51,19,10,0,26,0
1517,1517,BIHAR,BHAGALPUR,2003,45,57,13,33,0,107,0
2245,2245,BIHAR,BHAGALPUR,2004,63,59,12,13,0,226,0
2977,2977,BIHAR,BHAGALPUR,2005,75,52,18,15,0,55,0
3710,3710,BIHAR,BHAGALPUR,2006,43,44,19,19,1,22,0
4450,4450,BIHAR,BHAGALPUR,2007,25,59,21,33,2,16,0
5193,5193,BIHAR,BHAGALPUR,2008,35,98,27,35,5,120,0
5955,5955,BIHAR,BHAGALPUR,2009,28,44,15,2,0,47,0
6727,6727,BIHAR,BHAGALPUR,2010,22,80,20,12,0,42,0

In [11]:
df[(df['STATE/UT']=='BIHAR') & (df['DISTRICT']=='BHAGALPUR') & (df['Rape']>40) & (df['Importation of Girls']==0)]

,Unnamed: 0,STATE/UT,DISTRICT,Year,Rape,Kidnapping and Abduction,Dowry Deaths,Assault on women with intent to outrage her modesty,Insult to modesty of Women,Cruelty by Husband or his Relatives,Importation of Girls
1517,1517,BIHAR,BHAGALPUR,2003,45,57,13,33,0,107,0
2245,2245,BIHAR,BHAGALPUR,2004,63,59,12,13,0,226,0
2977,2977,BIHAR,BHAGALPUR,2005,75,52,18,15,0,55,0
3710,3710,BIHAR,BHAGALPUR,2006,43,44,19,19,1,22,0