In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/content/earthquake_1995-2023.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 19 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   title      1000 non-null   object
 1   magnitude  1000 non-null   float64
 2   date_time  1000 non-null   object
 3   cdi        1000 non-null   int64
 4   mmi        1000 non-null   int64
 5   alert      449 non-null    object
 6   tsunami    1000 non-null   int64
 7   sig        1000 non-null   int64
 8   net        1000 non-null   object
 9   nst        1000 non-null   int64
 10  dmin       1000 non-null   float64
 11  gap        1000 non-null   float64
 12  magType    1000 non-null   object
 13  depth      1000 non-null   float64
 14  latitude   1000 non-null   float64
 15  longitude  1000 non-null   float64
 16  location   994 non-null    object
 17  continent  284 non-null    object
 18  country    651 non-null    object
dtypes: float64(6), int64(5), object(8)
memory usage: 148.6+ KB

In [4]:
df.head()

,title,magnitude,date_time,cdi,mmi,alert,tsunami,sig,net,nst,dmin,gap,magType,depth,latitude,longitude,location,continent,country
0,"M 6.5 - 42 km W of Sola, Vanuatu",6.5,16-08-2023 12:47,7,4,green,0,657,us,114,7.177000,25.0,mww,192.955,-13.8814,167.1580,"Sola, Vanuatu",NaN,Vanuatu
1,"M 6.5 - 43 km S of Intipucá, El Salvador",6.5,19-07-2023 00:22,8,6,yellow,0,775,us,92,0.679000,40.0,mww,69.727,12.8140,-88.1265,"Intipucá, El Salvador",NaN,NaN
2,"M 6.6 - 25 km ESE of Loncopué, Argentina",6.6,17-07-2023 03:05,7,5,green,0,899,us,70,1.634000,28.0,mww,171.371,-38.1911,-70.3731,"Loncopué, Argentina",South America,Argentina
3,"M 7.2 - 98 km S of Sand Point, Alaska",7.2,16-07-2023 06:48,6,6,green,1,860,us,173,0.907000,36.0,mww,32.571,54.3844,-160.6990,"Sand Point, Alaska",NaN,NaN
4,M 7.3 - Alaska Peninsula,7.3,16-07-2023 06:48,0,5,NaN,1,820,at,79,0.879451,172.8,Mi,21.000,54.4900,-160.7960,Alaska Peninsula,NaN,NaN

In [5]:
df.tail(5)

,title,magnitude,date_time,cdi,mmi,alert,tsunami,sig,net,nst,dmin,gap,magType,depth,latitude,longitude,location,continent,country
995,"M 7.1 - 85 km S of Tungor, Russia",7.1,27-05-1995 13:03,0,9,NaN,0,776,us,0,0.0,0.0,mwb,11.0,52.629,142.827,"Tungor, Russia",Asia,Russia
996,"M 7.7 - 249 km E of Vao, New Caledonia",7.7,16-05-1995 20:12,0,4,NaN,0,912,us,0,0.0,0.0,mw,20.2,-23.008,169.900,"Vao, New Caledonia",NaN,NaN
997,"M 6.9 - 27 km NNW of Maubara, Timor Leste",6.9,14-05-1995 11:33,0,6,NaN,0,732,us,0,0.0,0.0,mw,11.2,-8.378,125.127,"Maubara, Timor Leste",NaN,Indonesia
998,"M 6.6 - 10 km W of Aianí, Greece",6.6,13-05-1995 08:47,0,9,NaN,0,670,us,0,0.0,0.0,mw,14.0,40.149,21.695,"Aianí, Greece",Europe,Greece
999,"M 7.1 - 14 km NE of Cabatuan, Philippines",7.1,05-05-1995 03:53,0,7,NaN,0,776,us,0,0.0,0.0,mw,16.0,12.626,125.297,"Cabatuan, Philippines",NaN,Philippines

In [6]:


df[(df['date_time']>'27-01-1995')]

,title,magnitude,date_time,cdi,mmi,alert,tsunami,sig,net,nst,dmin,gap,magType,depth,latitude,longitude,location,continent,country
12,M 6.6 - south of the Fiji Islands,6.6,28-04-2023 03:13,0,2,green,0,670,us,52,5.123,50.0,mww,598.467,-25.2657,178.424,the Fiji Islands,NaN,NaN
51,"M 7.0 - 11 km NE of Bantay, Philippines",7.0,27-07-2022 00:43,9,8,yellow,1,1351,us,152,5.276,22.0,mww,33.729,17.5978,120.809,"Bantay, Philippines",Asia,Philippines
57,M 7.0 - southeast of the Loyalty Islands,7.0,31-03-2022 05:44,6,4,green,1,763,us,0,2.705,26.0,mww,10.000,-22.5732,170.349,the Loyalty Islands,NaN,NaN
58,"M 6.9 - 284 km ESE of Tadine, New Caledonia",6.9,30-03-2022 20:56,6,4,green,1,738,us,0,2.697,42.0,mww,10.000,-22.7200,170.277,"Tadine, New Caledonia",NaN,NaN
65,M 6.5 - Kermadec Islands region,6.5,29-01-2022 02:46,7,4,green,1,651,us,0,1.088,57.0,mww,8.000,-29.5350,-176.729,Kermadec Islands region,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
956,"M 7.2 - 58 km WSW of Panguna, Papua New Guinea",7.2,29-04-1996 14:40,0,6,NaN,0,798,us,0,0.000,0.0,mwc,44.000,-6.5180,154.999,"Panguna, Papua New Guinea",NaN,Papua New Guinea
985,"M 6.6 - 95 km SW of Etchoropo, Mexico",6.6,28-08-1995 10:46,0,5,NaN,0,670,us,0,0.000,0.0,mwb,12.200,26.0920,-110.284,"Etchoropo, Mexico",NaN,NaN
991,"M 8.0 - 36 km NNE of Antofagasta, Chile",8.0,30-07-1995 05:11,0,8,NaN,0,985,us,0,0.000,0.0,mw,45.600,-23.3400,-70.294,Ant,South America,Chile
993,"M 6.6 - 0 km ESE of Isangel, Vanuatu",6.6,29-06-1995 12:24,0,5,NaN,0,670,us,0,0.000,0.0,mw,139.400,-19.5440,169.287,"Isangel, Vanuatu",NaN,Vanuatu
995,"M 7.1 - 85 km S of Tungor, Russia",7.1,27-05-1995 13:03,0,9,NaN,0,776,us,0,0.000,0.0,mwb,11.000,52.6290,142.827,"Tungor, Russia",Asia,Russia

In [7]:
df[(df['magnitude']>=5.5)]

,title,magnitude,date_time,cdi,mmi,alert,tsunami,sig,net,nst,dmin,gap,magType,depth,latitude,longitude,location,continent,country
0,"M 6.5 - 42 km W of Sola, Vanuatu",6.5,16-08-2023 12:47,7,4,green,0,657,us,114,7.177000,25.0,mww,192.955,-13.8814,167.1580,"Sola, Vanuatu",NaN,Vanuatu
1,"M 6.5 - 43 km S of Intipucá, El Salvador",6.5,19-07-2023 00:22,8,6,yellow,0,775,us,92,0.679000,40.0,mww,69.727,12.8140,-88.1265,"Intipucá, El Salvador",NaN,NaN
2,"M 6.6 - 25 km ESE of Loncopué, Argentina",6.6,17-07-2023 03:05,7,5,green,0,899,us,70,1.634000,28.0,mww,171.371,-38.1911,-70.3731,"Loncopué, Argentina",South America,Argentina
3,"M 7.2 - 98 km S of Sand Point, Alaska",7.2,16-07-2023 06:48,6,6,green,1,860,us,173,0.907000,36.0,mww,32.571,54.3844,-160.6990,"Sand Point, Alaska",NaN,NaN
4,M 7.3 - Alaska Peninsula,7.3,16-07-2023 06:48,0,5,NaN,1,820,at,79,0.879451,172.8,Mi,21.000,54.4900,-160.7960,Alaska Peninsula,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,"M 7.1 - 85 km S of Tungor, Russia",7.1,27-05-1995 13:03,0,9,NaN,0,776,us,0,0.000000,0.0,mwb,11.000,52.6290,142.8270,"Tungor, Russia",Asia,Russia
996,"M 7.7 - 249 km E of Vao, New Caledonia",7.7,16-05-1995 20:12,0,4,NaN,0,912,us,0,0.000000,0.0,mw,20.200,-23.0080,169.9000,"Vao, New Caledonia",NaN,NaN
997,"M 6.9 - 27 km NNW of Maubara, Timor Leste",6.9,14-05-1995 11:33,0,6,NaN,0,732,us,0,0.000000,0.0,mw,11.200,-8.3780,125.1270,"Maubara, Timor Leste",NaN,Indonesia
998,"M 6.6 - 10 km W of Aianí, Greece",6.6,13-05-1995 08:47,0,9,NaN,0,670,us,0,0.000000,0.0,mw,14.000,40.1490,21.6950,"Aianí, Greece",Europe,Greece
999,"M 7.1 - 14 km NE of Cabatuan, Philippines",7.1,05-05-1995 03:53,0,7,NaN,0,776,us,0,0.000000,0.0,mw,16.000,12.6260,125.2970,"Cabatuan, Philippines",NaN,Philippines

In [8]:
df[(df['country']=='Russia')]

,title,magnitude,date_time,cdi,mmi,alert,tsunami,sig,net,nst,dmin,gap,magType,depth,latitude,longitude,location,continent,country
141,"M 7.0 - 95 km ENE of Kuril’sk, Russia",7.0,13-02-2020 10:33,5,6,yellow,1,770,us,0,4.501,25.0,mww,143.0,45.6161,148.959,"Kuril’sk, Russia",Asia,Russia
248,"M 6.6 - 81 km NNE of Ust’-Kamchatsk Staryy, Ru...",6.6,29-03-2017 04:09,6,7,yellow,1,671,us,0,4.591,14.0,mww,17.0,56.9401,162.786,"Ust’-Kamchatsk Staryy, Russia",Asia,Russia
293,"M 7.2 - 80 km S of Mil’kovo, Russia",7.2,30-01-2016 03:25,3,7,green,1,799,us,0,0.958,17.0,mww,177.0,53.9776,158.546,"Mil’kovo, Russia",Asia,Russia
433,"M 7.2 - 252 km ENE of Kuril’sk, Russia",7.2,19-04-2013 03:05,5,7,green,1,804,us,770,0.000,10.1,mww,110.0,46.2210,150.788,"Kuril’sk, Russia",Asia,Russia
441,"M 6.6 - 183 km SW of Belaya Gora, Russia",6.6,14-02-2013 13:13,0,7,green,1,670,us,697,0.000,15.3,mww,11.0,67.6310,142.508,"Belaya Gora, Russia",Asia,Russia
480,"M 6.7 - 38 km NE of Saryg-Sep, Russia",6.7,26-02-2012 06:17,7,7,NaN,0,833,us,596,0.000,13.4,mww,12.0,51.7080,95.991,"Saryg-Sep, Russia",Asia,Russia
484,"M 6.6 - 45 km NNE of Saryg-Sep, Russia",6.6,27-12-2011 15:21,0,7,NaN,0,670,us,545,0.000,17.6,mww,15.0,51.8420,95.911,"Saryg-Sep, Russia",Asia,Russia
656,"M 6.5 - 81 km ESE of Ozernovskiy, Russia",6.5,24-08-2006 21:50,0,6,NaN,0,650,us,700,0.000,47.4,mwb,43.0,51.1480,157.522,"Ozernovskiy, Russia",Asia,Russia
660,"M 6.6 - 42 km NNW of Tilichiki, Russia",6.6,22-05-2006 11:12,0,7,NaN,0,670,us,548,0.000,28.0,mwc,19.0,60.7720,165.743,"Tilichiki, Russia",Asia,Russia
666,"M 6.6 - 80 km E of Tilichiki, Russia",6.6,29-04-2006 16:58,0,8,NaN,0,670,us,645,0.000,28.4,mwc,11.0,60.4910,167.516,"Tilichiki, Russia",Asia,Russia
667,"M 7.6 - 80 km NE of Tilichiki, Russia",7.6,20-04-2006 23:25,0,8,NaN,0,889,us,579,0.000,18.5,mwc,22.0,60.9490,167.089,"Tilichiki, Russia",Asia,Russia
724,"M 6.9 - 24 km ENE of Atlasovo, Russia",6.9,10-06-2004 15:19,0,5,NaN,0,732,us,798,0.000,31.2,mwb,188.6,55.6820,160.003,"Atlasovo, Russia",Asia,Russia
743,"M 6.7 - 9 km S of Aktash, Russia",6.7,01-10-2003 01:03,0,7,NaN,0,691,us,643,0.000,24.5,mwb,10.0,50.2110,87.721,"Aktash, Russia",Asia,Russia
745,"M 7.3 - 29 km S of Aktash, Russia",7.3,27-09-2003 11:33,0,7,NaN,0,820,us,667,0.000,24.5,mwb,16.0,50.0380,87.813,"Aktash, Russia",Asia,Russia
753,"M 6.9 - 25 km ESE of Atlasovo, Russia",6.9,16-06-2003 22:08,0,5,NaN,0,732,us,733,0.000,26.7,mwb,174.8,55.4920,159.999,"Atlasovo, Russia",Asia,Russia
835,"M 6.8 - 35 km SSE of Uglegorsk, Russia",6.8,04-08-2000 21:13,0,7,NaN,0,711,us,593,0.000,0.0,mwc,10.0,48.7860,142.246,"Uglegorsk, Russia",Asia,Russia
909,"M 7.8 - 156 km S of Ust’-Kamchatsk Staryy, Russia",7.8,05-12-1997 11:26,0,7,NaN,0,936,us,0,0.000,0.0,mwc,33.0,54.8410,162.035,"Ust’-Kamchatsk Staryy, Russia",Asia,Russia
969,"M 6.6 - 106 km NE of Yelizovo, Russia",6.6,01-01-1996 09:57,0,7,NaN,0,670,us,0,0.000,0.0,ms,33.0,53.8260,159.586,"Yelizovo, Russia",Asia,Russia
995,"M 7.1 - 85 km S of Tungor, Russia",7.1,27-05-1995 13:03,0,9,NaN,0,776,us,0,0.000,0.0,mwb,11.0,52.6290,142.827,"Tungor, Russia",Asia,Russia

In [9]:
X = df.drop("tsunami",axis=1)
Y = df["tsunami"]

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train,X_test,Y_train,Y_train = train_test_split(X,Y,train_size=0.2)

In [12]:
from sklearn.linear_model import LinearRegression

In [13]:
model =LinearRegression()

ValueError: could not convert string to float: 'M 6.6 - 37 km WNW of Poso, Indonesia'